(library
 (name carolina_handler)
 (wrapped false)
 (modules
  Prims
  FStar_UInt32
  FStar_Char
  FStar_String
  FStar_List_Tot_Base
  Carolina)
 (libraries batteries zarith stdint)
 (flags :standard -w -6-8-27-32-33-37-39)
 (preprocess
  (pps ppx_deriving.show ppx_deriving_yojson)))

(executable
 (name test)
 (modules Test)
 (flags :standard -warn-error +A)
 (link_flags :standard -cclib -lpq)
 (libraries threads carolina_server carolina_handler unix zarith))

(library
 (name carolina_server)
 (wrapped false)
 (modules Catalog Serve)
 (flags :standard -warn-error +A)
 (foreign_stubs
  (language c)
  (names pq_stubs)
  (flags -I/usr/include/postgresql -O2 -Wall -Wextra -Werror))
 (c_library_flags -lpq)
 (libraries threads carolina_handler unix zarith))

(executable
 (name server)
 (modules Server)
 (flags :standard -warn-error +A)
 (libraries carolina_server))
